server:
  port: 8800
mybatis-plus:
  mapper-locations: classpath:com/office/auth/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-field: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.15.59.5:3306/office_oa?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: SSxx123456.
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8d


#knife4j:
#  # 开启增强配置
#  enable: true
#  basic:
#    enable: true
#    # Basic认证用户名
#    username: test
#    # Basic认证密码
#    password: 123